version: "3.8"

services:
  postgres:
    image: ankane/pgvector
    container_name: autoriskai_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: autoriskai_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
